#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mautrix_discord"
name = "Matrix-Discord bridge"
description.en = "Matrix / Synapse puppeting bridge for Discord"
description.fr = "Passerelle Matrix / Synapse pour Discord"

version = "0.6.4~ynh1"

maintainers = ["fflorent"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "AGPL-3.0-or-later"
admindoc = "https://docs.mau.fi/bridges/go/discord/index.html"
code = "https://github.com/mautrix/discord"

fund = "https://github.com/sponsors/tulir"

[integration]
yunohost = ">= 11.1.21"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "100M"
ram.build = "256M"
ram.runtime = "1024M"

[install]
    [install.synapse_instance]
    ask.en = "Choose the local Synapse instance to communicate with mautrix_discord."
    ask.fr = "Choisissez l'instance Synapse qui doit communiquer avec mautrix_discord."
    type = "app"
    pattern.regexp = "synapse(__)*[0-9]*"
    pattern.error = "Invalid app selected. Please select a Synapse instance."
    help.en = "Usually the Synapse instances contain a number after it is installed more than one time. E.g. synapse__1 will be the second instance."
    help.fr = "En général, les instances de Synapse contiennent un numéro après avoir été installées plus d'une fois. Par exemple, synapse__1 sera la deuxième instance."
    default = "synapse"

    [install.botname]
    ask.en = "Choose a local Synapse user name for the Discord bot"
    ask.fr = "Choisissez un nom d'utilisateur Synapse local pour le robot Discord"
    type = "string"
    example = "discordbot"
    help.en = "A system user will be created. Invite @discordbot:localsynapse.servername from an authorized Matrix account to start bridging.Give the Matrix server_name, not the full domain/URL."
    help.fr = "Un utilisateur système sera créé. Inviter @discordbot:localsynapse.servername depuis un compte Matrix autorisé pour démarrer une passerelle.Donner le nom du serveur Matrix, pas le domaine/URL complet."
    default = "discordbot"

    [install.botadmin]
    ask.en = "Choose the Matrix account administrator of the Discord bot"
    ask.fr = "Choisissez le compte Matrix administrateur du robot Discord"
    type = "string"
    example = "@johndoe:localsynapse.servername or @johndoe:matrix.org"
    help.en = "The administrator does not need to be a local Synapse account. Valid formats are @johndoe:localsynapse.servername or @johndoe:matrix.org"
    help.fr = "L'administrateur peut ne pas être un compte local Synapse. Les formats valables sont @johndoe:localsynapse.servername or @johndoe:matrix.org"

    [install.botusers]
    ask.en = "Choose Matrix user(s) authorized to bridge with the Discord bot."
    ask.fr = "Choisissez le/les compte(s) Matrix autorisés à utiliser la passerelle Discord."
    type = "string"
    example = "@johndoe:server.name or server.name or *"
    

    [install.bot_synapse_adm]
    ask.en = "Give the Discord bot administrator rights to the Synapse instance?"
    ask.fr = "Donner au robot Discord des droits administrateur à l'instance Synapse ?"
    type = "boolean"
    help.en = "If true, the bot can group Discord chats in a Matrix space.Not required if you set up Synapse so that non-admins are authorized to create communities."
    help.fr = "Si true, le robot groupera les conversations Discord dans une communauté Matrix.Pas nécessaire si vous avez réglé Synapse pour qu'il autorise les non-admin à créer des communautés."
    default = true

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        extract = false
        rename = "mautrix-discord"

        amd64.url = "https://github.com/mautrix/discord/releases/download/v0.6.5/mautrix-discord-amd64"
        amd64.sha256 = "c89e2fdd6f5de28ae84d7f8ced27e174e8592364efd69c0ca6e8679e5c151489"
        arm64.url = "https://github.com/mautrix/discord/releases/download/v0.6.5/mautrix-discord-arm64"
        arm64.sha256 = "080b520871a51ddbe866ad83c889d47323452e6c25ee1b785e04a690884a77d9"
        armhf.url = "https://github.com/mautrix/discord/releases/download/v0.6.5/mautrix-discord-arm"
        armhf.sha256 = "e3a9eb3f64dc6d9e568f34f79b0b22cd08584c01779d22788ee6e966f5cde827"


    [resources.system_user]
    home = "/opt/yunohost/__APP__"

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.permissions]
    main.allowed = "all_users"
    main.auth_header = false

    [resources.ports]
    main.default = 29334

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
